### ISSUE TITLE
[iOS] "Received an invalid notification content" message is displayed in console when tapping or opening Firebase notification.

### ISSUE THREAD

**Issue by MaheshKumarM-SCE** [rafaelsetragni/awesome_notifications#175]
Android: Firebase notification is working fine in Android.

- Usually FirebaseMessaging.onMessageOpenedApp is triggered when tapping on the FCM notification. But after including awesome_notification in pubspec.yaml the FirebaseMessaging.onMessageOpenedApp is not triggered when tapping on the notification.
- And also FirebaseMessaging.instance.getInitialMessage() is not called when opening the app by tapping on the notification while app is terminated. This usually works.
- This issue occurs only in IOS, it works fine in Android. This problem occurred after including the  awesome_notification. 

Please help in sorting this issue.

**Comment by rafaelsetragni** [comment]
I did a test branch to check if the problem could be solved with a little change. Try to put the declaration bellow inside your `pubspec.yaml` file:

```yaml
  awesome_notifications: #^0.0.6+7
    git:
      url: https://github.com/rafaelsetragni/awesome_notifications.git
      ref: 54dbf1d
```

Also, put the code bellow inside your `pubspec.yaml`, to allow to use direrctely GitHub repositories in your project, above the tag `description`:

```yaml
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
```

And finally run `pub get` to check if the problem is solved with this fix.

**Comment by MaheshKumarM-SCE** [comment]
Thank you so much for helping me. I get this warning after tapping the notification -

Warning: UNUserNotificationCenter delegate received call to -userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: but the completion handler was never called.

**Comment by rafaelsetragni** [comment]
I did a new small improvement, because im obbligate to call completionHandler, but if i do it, i gonna cancel any other processment. 

Replace the git ref tag from `c968836` to `f9405a8` and execute your tests again:

```yaml
  awesome_notifications: #^0.0.6+7
    git:
      url: https://github.com/rafaelsetragni/awesome_notifications.git
      ref: f9405a8
```
