### ISSUE TITLE
Awesome Notifications does not build 

### ISSUE THREAD

**Issue by ItsWajdy** [rafaelsetragni/awesome_notifications#630]
## **1 - Describe the bug**

Adding the `awesome_notifications: ^0.7.4+1` dependency to the `pubspec.yaml` file in my Flutter project produces errors on build and/or run

## **2 - Provide us as much information as possible**

* Contents of `pubspec.yaml`
```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.16
  firebase_storage: ^10.2.16
  firebase_crashlytics: ^2.8.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  equatable: ^2.0.3
  responsive_framework: ^0.1.7
  expandable: ^5.0.1
  auto_size_text: ^3.0.0
  flutter_svg: ^1.1.0
  flutter_svg_provider: ^1.0.3
  percent_indicator: ^4.2.2
  flex_color_picker: ^2.5.0
  flutter_platform_widgets: ^2.0.0
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  form_field_validator: ^1.1.0
  fluttertoast: ^8.0.8
  humanizer: ^2.0.0
  persistent_bottom_nav_bar: ^4.0.2
  clipboard: ^0.1.3
  cloud_functions: ^3.3.3
  awesome_notifications: ^0.7.4+1
```
* How are you initializing the plugin
```
await _notifications.initialize(null, []);

_notifications.isNotificationAllowed().then((isAllowed) {
  if (!isAllowed) {
    // This is just a basic example. For real apps, you must show some
    // friendly dialog box before call the request method.
    // This is very important to not harm the user experience
    _notifications.requestPermissionToSendNotifications();
  }
});
```
* The output of `flutter doctor` command
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.22621.755], locale en-US)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2021.1)
[✓] VS Code (version 1.72.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

## **3 - How To Reproduce the Error**

1. Add `awesome_notifications: ^0.7.4+1` to `pubspec.yaml`
2. Run from Android Studio
3. See error
```
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:40:26: Error: Type 'DecoderBufferCallback' not found.
      ResourceImage key, DecoderBufferCallback decode) {
                         ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:48:26: Error: Type 'DecoderBufferCallback' not found.
      ResourceImage key, DecoderBufferCallback decode) async {
                         ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/awesome_notifications_method_channel.dart:186:10: Error: Type 'Uint8List' not found.
  Future<Uint8List?> getDrawableData(String drawablePath) async {
         ^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:21:7: Error: The non-abstract class 'ResourceImage' is missing implementations for these members:
 - ImageProvider.load
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ResourceImage extends ImageProvider<ResourceImage> {
      ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/image_provider.dart:567:24: Context: 'ImageProvider.load' is defined here.
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 32s
Exception: Gradle task assembleDebug failed with exit code 1
```

## **4 - Expected behavior**
The app to build
