### ISSUE TITLE
Badge works incompatible in release and debug modes.

### ISSUE THREAD

**Issue by tyypgzl** [rafaelsetragni/awesome_notifications#666]
## **1 - Describe the bug**

Each time the createNotification function is run in debug mode, the badge increases automatically. In release mode, this does not work properly.

I was not sure whether it was a bug or a quest because there was not enough information to use the badge.

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

<details><summary>pubspec.yaml</summary>

```yaml
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.2
  pin_code_fields: ^7.4.0
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.2.1
  flutter_svg: ^1.0.3
  lottie: ^2.0.0
  badges: ^2.0.3

  #Cache
  shared_preferences: ^2.0.13

  #l10n
  intl: ^0.17.0

  #Network
  connectivity_plus: ^3.0.2

  #Utils
  easy_logger: ^0.0.2
  flutter_countdown_timer: ^4.1.0
  image_picker: ^0.8.6
  uuid: ^3.0.6
  timezone: ^0.9.0
  device_info_plus: ^8.0.0

  #Router
  auto_route: ^5.0.1

  #Dependency Injection
  get_it: ^7.2.0

  #Bloc:
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  equatable: ^2.0.5

  #Responsive
  responsive_sizer: ^3.1.1
  responsive_builder: ^0.4.3

  #Theme
  flex_color_scheme: ^6.0.1

  #Syncfussion
  syncfusion_flutter_calendar: ^20.2.50
  syncfusion_flutter_datepicker: ^20.3.50
  syncfusion_localizations: ^20.3.48

  #JSON
  json_annotation: ^4.7.0

  #Firebase
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
  firebase_messaging: ^14.1.2
  firebase_storage: ^11.0.6
  firebase_crashlytics: ^3.0.6

  #Notification
  awesome_notifications: ^0.7.4+1

  #Form Field
  cat_form_field:
    git:
      url: https://cerenyasa97@bitbucket.org/cerenyasa97/cat_form_field.git
      ref: master

  #Core
  collection: ^1.16.0

  #url launch
  url_launcher: ^6.1.6

  #share
  share_plus: ^6.2.0

  #Path
  path: ^1.8.2
  path_provider: ^2.0.11


dev_dependencies:
  flutter_test:
    sdk: flutter

  #Static Analyze
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.0.1

  #Generator
  build_runner: ^2.2.1
  auto_route_generator: ^5.0.2
  json_serializable: ^6.5.1

```
</details>

* What platform did you found the issue : Android and IOS
* What devices did you found the issue Pixel 6 Emulator , Xiaomi Redmi Note 8 , Iphone 13 Emulator  , Iphone XS
* How are you initializing the plugin : There are no errors.
* How are you creating the notification : There are no errors. 

<details> 
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.6 21G115 darwin-arm, locale en-TR)
    • Flutter version 3.3.1 on channel stable at /Users/tayyipguzel/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (3 months ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/tayyipguzel/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

## **3 - How To Reproduce the Error**

In debug mode, create a new notification with the createNotification function and get it with the getBadgeCount function. The number of badges is increasing automatically.

The number of badges does not increase when repeating the same process in release mode.

## **4 - Expected behavior**
If we are going to manage the number of badges with the setGlobalBadgeCounter and resetGlobalBadge function and I trigger it every time a notification comes.

But if awesome_notification will manage this, the number of notifications should automatically increase for each mode(Release,debug) every time a notification is received.

## **5 - Screenshots**
None

## **6 - Additional context**
None
