### ISSUE TITLE
Swift Compiler Error (Xcode): No such module 'shared_preferences_ios' when i did extra part for background notification

### ISSUE THREAD

**Issue by nurhazbiy** [rafaelsetragni/awesome_notifications#708]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

Swift Compiler Error (Xcode): No such module 'shared_preferences_ios'

## **2 - Provide us as much information as possible**

hi, suddenly out of nowhere, i can't build my apps on ios anymore, i suspect because of this step. here is the error logs

```
Swift Compiler Error (Xcode): Cannot find 'FLTSharedPreferencesPlugin' in scope
/Users/hazbiy/Data/Kerja/Freelance/Project/Risearrow/Flutter/ios/Runner/AppDelegate.swift:17:12

Encountered error while building for device.
```

I think it's because i remove shared preferences on my main package because i moved it on my secondary packages, and when i check on pubscpec.lock, i can't find any line stating that shared_preferences_ios is installed (meanwhile all other shared_preferences is installed, even for web and linux). does it mean i need to manually include it in my apps? i thought it would be included by the awesome notification package

here is my pubspec.lock
```
  ...
  rxdart:
    dependency: transitive
    description:
      name: rxdart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.27.7"
  shared_preferences:
    dependency: transitive
    description:
      name: shared_preferences
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.16"
  shared_preferences_android:
    dependency: transitive
    description:
      name: shared_preferences_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.14"
  shared_preferences_foundation:
    dependency: transitive
    description:
      name: shared_preferences_foundation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  shared_preferences_linux:
    dependency: transitive
    description:
      name: shared_preferences_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.2"
  shared_preferences_platform_interface:
    dependency: transitive
    description:
      name: shared_preferences_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  shared_preferences_web:
    dependency: transitive
    description:
      name: shared_preferences_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  shared_preferences_windows:
    dependency: transitive
    description:
      name: shared_preferences_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.2"
  shelf:
    dependency: transitive
    description:
      name: shelf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.0"
  ...
```

## **3 - How To Reproduce the Error**

1. Create Clean project
2. Include awesome notification
3. Do extra step for background notification by adding the codes on appdelegate
4. Build Ios

## **4 - Expected behavior**
Build should be successful, because i haven't change anything on appdelegate before i cannot build anymore
