### ISSUE TITLE
DecoderBufferCallback/Uint8List Not Found on Flutter 3.0.4/Dart 2.17.5

### ISSUE THREAD

**Issue by Muhammad-Mohsen** [rafaelsetragni/awesome_notifications#741]
Hi, I'm using version `0.7.4+1` with Flutter version `3.0.4` and Dart version `2.17.5`
I'm getting the below errors
```
/C:/Flutter/sdk-3.0.4/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/awesome_notifications_method_channel.dart:186:10: Error: Type 'Uint8List' not found.
  Future<Uint8List?> getDrawableData(String drawablePath) async {
```
```
/C:/Flutter/sdk-3.0.4/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:48:26: Error: Type 'DecoderBufferCallback' not found.
      ResourceImage key, DecoderBufferCallback decode) async {
```
I saw in the documentation that these were deprecated/added since v2.12

However, when I looked at the Flutter [3.0.4 source](https://github.com/flutter/flutter/blob/3.0.4/packages/flutter/lib/src/painting/image_provider.dart), I found that the older `DecoderCallback` is still used.

I will upgrade Flutter to 3.3.0 and try again, but I just wanted to make sure that I didn't mess anything up.
Let me know if I can provide you with any other information.

Thanks.

#### `flutter doctor` output:
```
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19044.2604], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.23)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[!] Android Studio (version 2022.1)
    X Unable to find bundled Java version.
[√] IntelliJ IDEA Community Edition (version 2020.2)
[√] VS Code, 64-bit edition (version 1.76.1)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

#### pubspec.yaml
```
environment:
  sdk: ">=2.17.0 <3.0.0" # references the dart sdk, not flutter!

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.9
  file_picker: ^4.6.1
  permission_handler: 8.2.0
  app_settings: ^4.1.8
  is_first_run: ^1.0.0
  flutter_secure_storage: ^5.1.0
  package_info_plus: ^1.4.2

  web_socket_channel: ^2.2.0
  flutter_webrtc: ^0.9.7
  connectivity_plus: ^2.2.1
  phone_state: ^1.0.2 # to send WRTC_HOLD if the device receives a call

  awesome_notifications: ^0.7.4 # < 0.8.x
  flutter_ringtone_player: ^3.2.0
  sound_mode: ^2.0.2
  vibration: ^1.7.4-nullsafety.0
  proximity_sensor: ^1.0.4

  # cupertino_icons: ^1.0.2 # I don't think this is needed anymore

  http: ^0.13.5 # used for verification api

  # BACKGROUND OPERATION
  move_to_background: ^1.0.2
  flutter_background:
    path: packages/flutter_background
  geolocator: ^9.0.2

  # WEBVIEWS
  flutter_inappwebview: ^5.4.3+7 # android/ios
  webview_windows: ^0.1.6
  flutter_macos_webview:
    path: packages/flutter_macos_webview

  win_toast: ^0.0.2 # windows notification center
  bitsdojo_window: ^0.1.2 # window sizing on macos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/Ring_Logo.jpg"
  remove_alpha_ios: true


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

```
