### ISSUE TITLE
error in a redirect to a specific page in the app when terminated 

### ISSUE THREAD

**Issue by dj-yacine-flutter** [rafaelsetragni/awesome_notifications#794]
To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:
Hi ,
 Thanks for this package it's really useful . But there is small problem :
## **1 - Describe the bug**

- when i click on  the schedule notification when the app is killed in android 11 or less it redirects me to the specific page in the app . but in android 11 and above the notification  doesn't redirect me to the specific page when the app is killed but if the app is in the background or foreground it work fine 

## **2 - pubspec.yaml**
```Yaml
environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # dependencies
  equatable: ^2.0.5
  file_picker: ^5.3.0
  flex_color_scheme: ^7.1.2
  flutter_bloc: ^8.1.3
  http: ^0.13.6
  path: ^1.8.3
  permission_handler: ^10.2.0
  retry: ^3.1.2
  shared_preferences: ^2.1.1
  intl: ^0.18.1
  tmdb_api: ^2.1.5
  cached_network_image: ^3.2.3
  auto_size_text: ^3.0.0
  flutter_carousel_slider: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  photo_view: ^0.14.0
  device_info_plus: ^9.0.2
  awesome_notifications: ^0.7.5-dev.2+1




dev_dependencies:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
```

## **3 - Flutter Doctor**
```sh
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.2, on Arch Linux 6.1.31-1-lts, locale en_US.UTF-8)
    • Flutter version 3.10.2 on channel stable at /home/dj-yacine/Languages && Frameworks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (9 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/dj-yacine/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /home/dj-yacine/Apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/dj-yacine/Apps/android-studio
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Arch Linux 6.1.31-1-lts
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.90

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
## **5 - Video**
Android 10 emulator 

https://github.com/rafaelsetragni/awesome_notifications/assets/127781608/1d59d2d9-d80d-4f94-a852-40a0bddd479a

Android 13 emulator 
 

https://github.com/rafaelsetragni/awesome_notifications/assets/127781608/3fdb96f1-fbb4-4429-bd86-b45ddf674fcd
