### ISSUE TITLE
PlatformException(SHARED_PREFERENCES_NOT_AVAILABLE, class j3.b isn't parameterized, sharedPreferences.get, null)

### ISSUE THREAD

**Issue by feriwnarta** [rafaelsetragni/awesome_notifications#814]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(SHARED_PREFERENCES_NOT_AVAILABLE, class j3.b isn't parameterized, sharedPreferences.get, null)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:296)
       at MethodChannelAwesomeNotifications.initialize(awesome_notifications_method_channel.dart:289)

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
* What platform did you found the issue
* What devices did you found the issue
* How are you initializing the plugin
* How are you creating the notification
* The output of `flutter doctor` command

OBS: To post a source code in your issue, please use the markdown below:

```Dart
print('Your source code goes here');
```

## **3 - How To Reproduce the Error**

...or if you prefer, you can provide us a simple example app on GitHub with the issue already reproduced instead of the steps 2 and 3.

**Comment by fdwl** [comment]
/flutter (32382): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(SHARED_PREFERENCES_NOT_AVAILABLE, class g2.b isn't parameterized, sharedPreferences.get, null)
E/flutter (32382): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
message_codecs.dart:1
E/flutter (32382): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
platform_channel.dart:1
E/flutter (32382): <asynchronous suspension>
E/flutter (32382): #2      MethodChannelAwesomeNotifications.initialize (package:awesome_notifications/awesome_notifications_method_channel.dart:299)
awesome_notifications_method_channel.dart:1
E/flutter (32382): <asynchronous suspension>
E/flutter (32382):

release mode

**Comment by matheus85** [comment]
Same problema here.

**Comment by incrediblezayed** [comment]
+1

**Comment by wurayan** [comment]
Got the same message error as @fdwl 
```
flutter doctor -v
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [versÆo 10.0.19045.3693], locale pt-BR)
    • Flutter version 3.13.9 on channel stable at C:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (4 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Usuario\AppData\Local\Android\sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [versÆo 10.0.19045.3693]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 119.0.6045.160
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 119.0.2151.44

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

Pubspec:
```
dependencies:
  awesome_notifications: ^0.8.2
  brasil_fields: ^1.14.0
  calendar_view: ^1.0.4
  device_calendar:
    git:
      url: https://github.com/builttoroam/device_calendar.git
      ref: develop
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5
  flutter_timezone: ^1.0.8
  flux_validator_dart: ^2.0.0
  internet_connection_checker: ^1.0.0+1
  intl: any
  location: ^5.0.3
  maps_launcher: ^2.2.0
  mysql_client: ^0.0.27
  package_info_plus: ^4.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  url_launcher: ^6.2.1
```
