### ISSUE TITLE
Android 14 support

### ISSUE THREAD

**Issue by guyluz11** [rafaelsetragni/awesome_notifications#846]
Android 14 is not out yet on the market but we can already get ready for it with the Android emulator.

 I have tested `awesome_notifications` with it and it seems that it is kind of not working.
 I sent notifications for the current time and most of them didn't arrive, one arrived in the next minute but the other didn't arrive at all.

This issue is in general test `awesome_notifications` for Android 14 and follows its status, not a specific bug.

**Comment by rafaelsetragni** [comment]
The last version now supports Flutter 3.13, Android 14 and iOS 17. You just need to add the pubspec.yaml below:

```yaml
  # Awesome plugins
  awesome_notifications_core: ^0.7.6 # use the latest available
  awesome_notifications: any # <- this version will be managed by core plugin
  awesome_notifications_fcm: any # <- this version will be managed by core plugin
```
