### ISSUE TITLE
[iOS] Silent Notificaiton is not working, issue related to displayOnBackground, playSound

### ISSUE THREAD

**Issue by Mickco** [rafaelsetragni/awesome_notifications#867]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

I have an app that suppose running location service in the background and push some silent notification in the background. I encounter the following issues when trying to do so.
1. Even displayOnBackground set to false, the device still displaying notification in home page.
2. Even in NotificationChannel, importance set to min, playSound set to false, the notification still displaying and play notification sound in home page.

## **2 - Provide us as much information as possible**

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
```
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  location: ^5.0.3
  permission_handler: ^11.0.1
  app_settings: ^5.1.1
  awesome_notifications_core: ^0.8.0 # <~ always ensure to use the latest version
  awesome_notifications: ^0.8.2 # <~ this version is managed by awesome_notifications_core package


dependency_overrides:
  intl: 0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

```

* What platform did you found the issue
iOS

* What devices did you found the issue
iPhone 14 Pro

* How are you initializing the plugin
<img width="734" alt="image" src="https://github.com/rafaelsetragni/awesome_notifications/assets/22823054/d50b3e69-a209-4622-a2af-d9cc423083c9">

* How are you creating the notification
<img width="1282" alt="image" src="https://github.com/rafaelsetragni/awesome_notifications/assets/22823054/e14f1c9c-a4f7-47c6-b572-cd67aeee9f4a">

## **3 - How To Reproduce the Error**

1. Use Location package https://pub.dev/packages/location and awesome notification package
2. Using Location package, enable background service and listen to location service
```
location.enableBackgroundMode(enable: true)
location.onLocationChanged.listen((LocationData currentLocation) {
    NotificationUtil.createOnGoingNoti(AwesomeNotifications(), _data);
});
```
3. Enable this after the app is opened. Then put the app in the background.
4. Should be able to observe the notification keep popping up

## **4 - Expected behavior**
After the app is put in the background, 
1. the notification should not be displayed
2. the device should not play notification sound
3. the device should not vibrate

## **5 - Screenshots**
![image](https://github.com/rafaelsetragni/awesome_notifications/assets/22823054/2bc8936d-4b64-48a3-bf26-dbd389909304)
