### ISSUE TITLE
Compiling for iOS 11.0, but module 'IosAwnCore' has a minimum deployment target of iOS 12.0

### ISSUE THREAD

**Issue by marylicious** [rafaelsetragni/awesome_notifications#892]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

I successfully installed the library for Android but the build is failing for iOS, these are the errors:

```
Compiling for iOS 11.0, but module 'IosAwnCore' has a minimum deployment target of iOS 12.0: /Users/user/Library/Developer/Xcode/DerivedData/Runner-agmtopjvkrdivlfuhretzmddtcry/Build/Products/Debug-iphonesimulator/IosAwnCore/IosAwnCore.framework/Modules/IosAwnCore.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

```

```
Failed to build module 'IosAwnFcmCore'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)', while this compiler is 'Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)'). Please select a toolchain which matches the SDK.
```

I checked literally all the targets and runner, also the pods and everything is over 12.0. But for some reason it doesn't compiles, I also added this post install script. I also checked the requirement of safe api and distribution

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
   flutter_additional_ios_build_settings(target)
   target.build_configurations.each do |config|
    config.build_settings['ENABLE_BITCODE']='NO'
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
    config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
    config.build_settings['IOS_DEPLOYMENT_TARGET'] = '12.0'
    
    target 'url_launcher_ios' do
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  
    #config.build_settings['IPHONEOS_SDKROOT']='12.0'
   end
  end
 end
```

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
* What platform did you found the issue
* What devices did you found the issue
* How are you initializing the plugin
* How are you creating the notification
* The output of `flutter doctor` command

```
Flutter 3.7.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ad6cd72c0 (8 months ago) • 2023-03-08 09:41:59 -0800
Engine • revision 1837b5be5f
Tools • Dart 2.19.4 • DevTools 2.20.1
```

```yaml


environment:
  sdk: ">=2.16.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: #allow internationalization
    sdk: flutter
  intl: ^0.18.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  string_to_hex: ^0.2.2
  infinite_scroll_pagination: 3.2.0
  #flutter_inappwebview: ^5.4.0
  #  http_proxy: ^1.2.0
  #  dio: ^4.0.4
  decorated_icon: ^1.2.1
  like_button: ^2.0.4
  flutter_riverpod: ^0.13.1+1
  miniplayer: ^1.0.0+2
  timeago: ^3.0.2
  audioplayers: ^1.0.1
  sqflite: ^2.0.3
  path: ^1.8.1
  duration: ^3.0.12
  #package_info_plus: ^2.0.0
  url_launcher: ^6.1.10
  cached_network_image: ^3.2.0
  #carousel_slider: ^4.2.1
  back_button_interceptor: ^6.0.0
  firebase_core: 2.8.0
  firebase_core_platform_interface: 4.5.3
  awesome_notifications: ^0.7.4+1
  awesome_notifications_fcm: 0.7.4+1
  flutter_secure_storage: ^8.1.0
  #yaml: ^3.1.1
  cryptography: ^2.5.0


dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter


```

## **3 - How To Reproduce the Error**

1. Build the library with the version below
